# Generated by Django 2.1 on 2018-12-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseblog', '0003_photocollection_portofilo_projects_storymodel_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='label',
            field=models.CharField(default='label', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='pic',
            field=models.ImageField(default='pic', upload_to='pic_folder/'),
            preserve_default=False,
        ),
    ]
