# Generated by Django 2.1 on 2018-12-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseblog', '0006_storymodel_sub_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
