# Generated by Django 2.1 on 2018-12-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseblog', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaptre1', models.CharField(max_length=255)),
                ('title_chap1', models.CharField(max_length=255)),
                ('contenu1', models.TextField()),
                ('pic_two', models.ImageField(upload_to='pic_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Pola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaptre', models.CharField(max_length=255)),
                ('title_chap', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('pic_one', models.ImageField(upload_to='pic_folder/')),
            ],
        ),
    ]
