# Generated by Django 2.1 on 2019-01-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseblog', '0010_auto_20190118_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pola',
            name='likes',
        ),
    ]
